services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: pactgerman
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: sh /app/wait_and_start.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - TRANSFORMERS_CACHE=/app/model_cache
      - HF_HOME=/app/model_cache

volumes:
  mysql_data: