# Generated by Django 5.1.2 on 2025-11-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlevel',
            name='errorlevelrussian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='coherence',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2-'), (3, '2'), (4, '2+'), (5, '3-'), (6, '3'), (7, '3+'), (8, '4-'), (9, '4'), (10, '4+'), (11, '5-'), (12, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='completeness',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2-'), (3, '2'), (4, '2+'), (5, '3-'), (6, '3'), (7, '3+'), (8, '4-'), (9, '4'), (10, '4+'), (11, '5-'), (12, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='educationlevel',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='selfassesment',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='selfrating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2-'), (3, '2'), (4, '2+'), (5, '3-'), (6, '3'), (7, '3+'), (8, '4-'), (9, '4'), (10, '4+'), (11, '5-'), (12, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='structure',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2-'), (3, '2'), (4, '2+'), (5, '3-'), (6, '3'), (7, '3+'), (8, '4-'), (9, '4'), (10, '4+'), (11, '5-'), (12, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='textgrade',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2-'), (3, '2'), (4, '2+'), (5, '3-'), (6, '3'), (7, '3+'), (8, '4-'), (9, '4'), (10, '4+'), (11, '5-'), (12, '5')], null=True),
        ),
    ]
